name: Sync Fork
on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual trigger
jobs:
  sync:
    runs-on: ubuntu-latest   # OS
    steps:
      - uses: pkeffect/open-webui
        with:
          owner: pkeffect
          base: main
          head: main
          token: ${{ secrets.GITHUB_TOKEN }}
